#!/bin/bash

declare -a arr=("$@")
declare -i n=$#

if [[ $n -eq 0 ]]; then
  echo "Empty array provided"
  exit 2
fi

for (( i = 0; i < $n; i++ )); do
  swapped=0
  for (( j = 0; j < $n-i-1; j++ )); do
    if [[ ${arr[$j]} > ${arr[$j+1]} ]]; then
      swapped=1
      tmp=${arr[$j]}
      arr[$j]=${arr[$j+1]}
      arr[$j+1]=$tmp
    fi
  done
  if [[ $swapped ]]; then
    break
  fi
done

echo "Result array:"
echo "${arr[*]}"


